# Linker configuration
server-id: 0
proxy-address: "127.0.0.1"
proxy-port-tcp: 23904
proxy-port-udp: 23905
proxy-connection-timeout: 5000
kryonet-logging: NONE
auth-password: "CHANGE_THIS_TO_YOUR_PASSWORD___IT_NEEDS_TO_BE_SECURE!"
# Messages
sector-welcome-message:
  - ''
  - '  &aWelcome on sector &7%name%&a (id: &7%id%&a)'
  - ''
sector-break-message: '&cYou can not destroy blocks that close to the sector border!'
sector-place-message: '&cYou can not build blocks that close to the sector border!'
sector-ignite-message: '&cYou can not ignite blocks that close to the sector border!'
sector-bucket-message: '&cYou can not pour out water/lava that close to the sector border!'
sector-border-close: '&2&lSector border: &f&l%distance%'